### PR TITLE
Create pr3.yaml

### PR DESCRIPTION
**Pull request by fischerscode**

### CODE REVIEW

**Comment by fischerscode** [comment]
@mtrezza Weird...

**Comment by mtrezza** [comment]
You mean that the file runs before being merged?

**Comment by fischerscode** [comment]
Yes
Edit: Maybe it's something in the settings.

**Comment by fischerscode** [comment]
Or it's because I'm the repo owner and I've created the PR... investigating.

**Comment by mtrezza** [comment]
Either that or it's because you already had an existing workflow which runs on PRs, so it's picked up in the PR. The Flutter repo has no workflow at all yet.

**Pull request closed without merging**
